version: "3.8"
services:
  api:
    build: ./backend
    container_name: api_backend
    ports:
      - "4000:4000"
  client:
    build: ./frontend
    container_name: client_frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
